ItemManager [Class]:
    +findSimulatedItemsInRadius(Vector3 center, float sqrRadius, List<InteractableItem> result)
    +takeItem(Transform item, byte to_x, byte to_y, byte to_rot, byte to_page)
    +dropItem(Item item, Vector3 point, bool playEffect, bool isDropped, bool wideSpread)
    +tellTakeItem(CSteamID steamID, byte x, byte y, uint instanceID)
    +ReceiveDestroyItem(byte x, byte y, uint instanceID, bool shouldPlayEffect)
    +askTakeItem(CSteamID steamID, byte x, byte y, uint instanceID, byte to_x, byte to_y, byte to_rot, byte to_page)
    +ReceiveTakeItemRequest(in ServerInvocationContext context, byte x, byte y, uint instanceID, byte to_x, byte to_y, byte to_rot, byte to_page)
    +tellClearRegionItems(CSteamID steamID, byte x, byte y)
    +ReceiveClearRegionItems(byte x, byte y)
    +askClearRegionItems(byte x, byte y)
    +askClearAllItems()
    +ServerClearItemsInSphere(Vector3 center, float radius)
    +spawnItem(byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID, bool shouldPlayEffect)
    +tellItem(CSteamID steamID, byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID)
    +ReceiveItem(byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID, bool shouldPlayEffect)
    +ReceiveItems(in ClientInvocationContext context)
    +tellItems(CSteamID steamID)
    +askItems(CSteamID steamID, byte x, byte y)

// Note this doesnt Contain All as it will take a long time to add all the obsolete stuff
EffectManager [Class]:
    +ReceiveUIEffectVisibility(short key, string childNameOrPath, bool visible)
    +ReceiveUIEffect4Args(ushort id, short key, string arg0, string arg1, string arg2, string arg3)
    +ReceiveUIEffect3Args(ushort id, short key, string arg0, string arg1, string arg2)
    +ReceiveUIEffect2Args(ushort id, short key, string arg0, string arg1)
    +ReceiveUIEffect1Arg(ushort id, short key, string arg0)
    +ReceiveUIEffect(ushort id, short key)
    +ReceiveEffectPositionRotation(Guid assetGuid, Vector3 position, Quaternion rotation)
    +ReceiveEffectPositionRotation_UniformScale(Guid assetGuid, Vector3 position, Quaternion rotation, float uniformScale)
    +ReceiveEffectPositionRotation_NonUniformScale(Guid assetGuid, Vector3 position, Quaternion rotation, Vector3 scale)
    +ReceiveEffectPoint(Guid assetGuid, Vector3 point)
    +ReceiveEffectPoint_UniformScale(Guid assetGuid, Vector3 point, float uniformScale)
    +ReceiveEffectPoint_NonUniformScale(Guid assetGuid, Vector3 point, Vector3 scale)
    +ReceiveEffectPointNormal(Guid assetGuid, Vector3 point, Vector3 normal)
    +ReceiveEffectPointNormal_UniformScale(Guid assetGuid, Vector3 point, Vector3 normal, float uniformScale)
    +ReceiveEffectPointNormal_NonUniformScale(Guid assetGuid, Vector3 point, Vector3 normal, Vector3 scale)
    +sendUIEffectImageURL(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, string url, bool shouldCache = true, bool forceRefresh = false)
    +sendUIEffectImageURL(short key, CSteamID steamID, bool reliable, string childNameOrPath, string url, bool shouldCache = true, bool forceRefresh = false)
    +sendUIEffectImageURL(short key, CSteamID steamID, bool reliable, string childNameOrPath, string url)
    +sendUIEffectText(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, string text)
    +sendUIEffectVisibility(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, bool visible)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1, string arg2, string arg3)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1, string arg2)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1, string arg2, string arg3)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1, string arg2)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0)
    +sendUIEffect(ushort id, short key, bool reliable)
    +TriggerFiremodeEffect(Vector3 position)
    +askEffectClearAll()
    +ReceiveEffectClearAll()
    +ClearEffectByGuid_AllPlayers(Guid assetGuid)
    +ClearEffectByGuid(Guid assetGuid, ITransportConnection transportConnection)
    +ClearEffectByID_AllPlayers(ushort id)
    +askEffectClearByID(ushort id, ITransportConnection transportConnection)
    +ClearEffect(EffectAsset asset)
    +ReceiveEffectClearByGuid(Guid assetGuid)
    +ReceiveEffectClearById(ushort id)
    +ReceiveUIEffectText(short key, string childNameOrPath, string text)
    +ReceiveUIEffectImageURL(short key, string childNameOrPath, string url, bool shouldCache, bool forceRefresh)
    +ReceiveEffectClicked(in ServerInvocationContext context, string buttonName)
    +ReceiveEffectTextCommitted(in ServerInvocationContext context, string inputFieldName, string text)
    +sendEffectTextCommitted(string inputFieldName, string text)
    +destroyUIEffect(short key)
    +createUIEffect(ushort id, short key)
    +gatherFormattingForUIEffect(Transform effect)
    +formatTextIntoUIEffect(Transform effect, params object[] args)
    +formatPluginHotkeysIntoUIEffect(Transform effect)
    +hookButtonsInUIEffect(Transform effect)
    +hookInputFieldsInUIEffect(Transform effect)
    +effect(ushort id, Vector3 point, Vector3 normal)
    +effect(Guid assetGuid, Vector3 point, Vector3 normal)
    +effect(EffectAsset asset, Vector3 point, Vector3 normal)
    +effect(ushort id, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(Guid assetGuid, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(EffectAsset asset, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(AssetReference<EffectAsset> assetRef, Vector3 position)
    +triggerEffect(TriggerEffectParameters parameters)
    +RegisterDebris(GameObject item)
    +askEffectClearByID(ushort id, CSteamID steamID)
    +tellEffectClearAll(CSteamID steamID)
    +sendEffect(ushort id, byte x, byte y, byte area, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, byte x, byte y, byte area, Vector3 point)
    +sendEffect(ushort id, float radius, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, float radius, Vector3 point)
    +sendEffect(ushort id, CSteamID steamID, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, CSteamID steamID, Vector3 point)
    +sendEffect(ushort id, ITransportConnection transportConnection, Vector3 point)
    +sendEffectReliable(ushort id, byte x, byte y, byte area, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, byte x, byte y, byte area, Vector3 point)
    +sendEffectReliable(ushort id, float radius, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, float radius, Vector3 point)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, Vector3 normal, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, CSteamID steamID, Vector3 point, Vector3 normal, Vector3 scale)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, CSteamID steamID, Vector3 point, Vector3 scale)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal, Vector3 scale)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 scale)

ChatManager [Class]:
    +receiveChatMessage(CSteamID speakerSteamID, string iconURL, EChatMode mode, Color color, bool isRich, string text)
    +ReceiveVoteStart(CSteamID origin, CSteamID target, byte votesNeeded)
    +ReceiveVoteUpdate(byte voteYes, byte voteNo)
    +ReceiveVoteStop(EVotingMessage message)
    +ReceiveVoteMessage(EVotingMessage message)
    +ReceiveSubmitVoteRequest(in ServerInvocationContext context, bool vote)
    +ReceiveCallVoteRequest(in ServerInvocationContext context, CSteamID target)
    +sendVote(bool vote)
    +sendCallVote(CSteamID target)
    +ReceiveChatEntry(CSteamID owner, string iconURL, EChatMode mode, Color color, bool rich, string text)
    +ReceiveChatRequest(in ServerInvocationContext context, byte flags, string text)
    +sendChat(EChatMode mode, string text)
    +clientSendMessage_UnityEvent(EChatMode mode, string text, ClientTextChatMessenger messenger)
    +serverSendMessage_UnityEvent(string text, Color color, string iconURL, bool useRichTextFormatting, ServerTextChatMessenger messenger)
    +say(CSteamID target, string text, Color color, bool isRich = false)
    +say(CSteamID target, string text, Color color, EChatMode mode, bool isRich = false)
    +say(string text, Color color, bool isRich = false)
    +serverSendMessage(string text, Color color, SteamPlayer fromPlayer = null, SteamPlayer toPlayer = null, EChatMode mode = EChatMode.SAY, string iconURL = null, bool useRichTextFormatting = false)
    +