ItemManager [Class]:
    +findSimulatedItemsInRadius(Vector3 center, float sqrRadius, List<InteractableItem> result)
    +takeItem(Transform item, byte to_x, byte to_y, byte to_rot, byte to_page)
    +dropItem(Item item, Vector3 point, bool playEffect, bool isDropped, bool wideSpread)
    +tellTakeItem(CSteamID steamID, byte x, byte y, uint instanceID)
    +ReceiveDestroyItem(byte x, byte y, uint instanceID, bool shouldPlayEffect)
    +askTakeItem(CSteamID steamID, byte x, byte y, uint instanceID, byte to_x, byte to_y, byte to_rot, byte to_page)
    +ReceiveTakeItemRequest(in ServerInvocationContext context, byte x, byte y, uint instanceID, byte to_x, byte to_y, byte to_rot, byte to_page)
    +tellClearRegionItems(CSteamID steamID, byte x, byte y)
    +ReceiveClearRegionItems(byte x, byte y)
    +askClearRegionItems(byte x, byte y)
    +askClearAllItems()
    +ServerClearItemsInSphere(Vector3 center, float radius)
    +spawnItem(byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID, bool shouldPlayEffect)
    +tellItem(CSteamID steamID, byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID)
    +ReceiveItem(byte x, byte y, ushort id, byte amount, byte quality, byte[] state, Vector3 point, uint instanceID, bool shouldPlayEffect)
    +ReceiveItems(in ClientInvocationContext context)
    +tellItems(CSteamID steamID)
    +askItems(CSteamID steamID, byte x, byte y)

// Note this doesnt Contain All as it will take a long time to add all the obsolete stuff
EffectManager [Class]:
    +ReceiveUIEffectVisibility(short key, string childNameOrPath, bool visible)
    +ReceiveUIEffect4Args(ushort id, short key, string arg0, string arg1, string arg2, string arg3)
    +ReceiveUIEffect3Args(ushort id, short key, string arg0, string arg1, string arg2)
    +ReceiveUIEffect2Args(ushort id, short key, string arg0, string arg1)
    +ReceiveUIEffect1Arg(ushort id, short key, string arg0)
    +ReceiveUIEffect(ushort id, short key)
    +ReceiveEffectPositionRotation(Guid assetGuid, Vector3 position, Quaternion rotation)
    +ReceiveEffectPositionRotation_UniformScale(Guid assetGuid, Vector3 position, Quaternion rotation, float uniformScale)
    +ReceiveEffectPositionRotation_NonUniformScale(Guid assetGuid, Vector3 position, Quaternion rotation, Vector3 scale)
    +ReceiveEffectPoint(Guid assetGuid, Vector3 point)
    +ReceiveEffectPoint_UniformScale(Guid assetGuid, Vector3 point, float uniformScale)
    +ReceiveEffectPoint_NonUniformScale(Guid assetGuid, Vector3 point, Vector3 scale)
    +ReceiveEffectPointNormal(Guid assetGuid, Vector3 point, Vector3 normal)
    +ReceiveEffectPointNormal_UniformScale(Guid assetGuid, Vector3 point, Vector3 normal, float uniformScale)
    +ReceiveEffectPointNormal_NonUniformScale(Guid assetGuid, Vector3 point, Vector3 normal, Vector3 scale)
    +sendUIEffectImageURL(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, string url, bool shouldCache = true, bool forceRefresh = false)
    +sendUIEffectImageURL(short key, CSteamID steamID, bool reliable, string childNameOrPath, string url, bool shouldCache = true, bool forceRefresh = false)
    +sendUIEffectImageURL(short key, CSteamID steamID, bool reliable, string childNameOrPath, string url)
    +sendUIEffectText(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, string text)
    +sendUIEffectVisibility(short key, ITransportConnection transportConnection, bool reliable, string childNameOrPath, bool visible)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1, string arg2, string arg3)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1, string arg2)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0, string arg1)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable, string arg0)
    +sendUIEffect(ushort id, short key, ITransportConnection transportConnection, bool reliable)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1, string arg2, string arg3)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1, string arg2)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0, string arg1)
    +sendUIEffect(ushort id, short key, bool reliable, string arg0)
    +sendUIEffect(ushort id, short key, bool reliable)
    +TriggerFiremodeEffect(Vector3 position)
    +askEffectClearAll()
    +ReceiveEffectClearAll()
    +ClearEffectByGuid_AllPlayers(Guid assetGuid)
    +ClearEffectByGuid(Guid assetGuid, ITransportConnection transportConnection)
    +ClearEffectByID_AllPlayers(ushort id)
    +askEffectClearByID(ushort id, ITransportConnection transportConnection)
    +ClearEffect(EffectAsset asset)
    +ReceiveEffectClearByGuid(Guid assetGuid)
    +ReceiveEffectClearById(ushort id)
    +ReceiveUIEffectText(short key, string childNameOrPath, string text)
    +ReceiveUIEffectImageURL(short key, string childNameOrPath, string url, bool shouldCache, bool forceRefresh)
    +ReceiveEffectClicked(in ServerInvocationContext context, string buttonName)
    +ReceiveEffectTextCommitted(in ServerInvocationContext context, string inputFieldName, string text)
    +sendEffectTextCommitted(string inputFieldName, string text)
    +destroyUIEffect(short key)
    +createUIEffect(ushort id, short key)
    +gatherFormattingForUIEffect(Transform effect)
    +formatTextIntoUIEffect(Transform effect, params object[] args)
    +formatPluginHotkeysIntoUIEffect(Transform effect)
    +hookButtonsInUIEffect(Transform effect)
    +hookInputFieldsInUIEffect(Transform effect)
    +effect(ushort id, Vector3 point, Vector3 normal)
    +effect(Guid assetGuid, Vector3 point, Vector3 normal)
    +effect(EffectAsset asset, Vector3 point, Vector3 normal)
    +effect(ushort id, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(Guid assetGuid, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(EffectAsset asset, Vector3 point, Vector3 normal, Vector3 scaleMultiplier)
    +effect(AssetReference<EffectAsset> assetRef, Vector3 position)
    +triggerEffect(TriggerEffectParameters parameters)
    +RegisterDebris(GameObject item)
    +askEffectClearByID(ushort id, CSteamID steamID)
    +tellEffectClearAll(CSteamID steamID)
    +sendEffect(ushort id, byte x, byte y, byte area, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, byte x, byte y, byte area, Vector3 point)
    +sendEffect(ushort id, float radius, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, float radius, Vector3 point)
    +sendEffect(ushort id, CSteamID steamID, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal)
    +sendEffect(ushort id, CSteamID steamID, Vector3 point)
    +sendEffect(ushort id, ITransportConnection transportConnection, Vector3 point)
    +sendEffectReliable(ushort id, byte x, byte y, byte area, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, byte x, byte y, byte area, Vector3 point)
    +sendEffectReliable(ushort id, float radius, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, float radius, Vector3 point)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, Vector3 normal, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, CSteamID steamID, Vector3 point, Vector3 normal, Vector3 scale)
    +sendEffectReliable(ushort id, CSteamID steamID, Vector3 point, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, CSteamID steamID, Vector3 point, Vector3 scale)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 normal, Vector3 scale)
    +sendEffectReliable(ushort id, ITransportConnection transportConnection, Vector3 point, float uniformScale)
    +sendEffectReliable_NonUniformScale(ushort id, ITransportConnection transportConnection, Vector3 point, Vector3 scale)

ChatManager [Class]:
    +receiveChatMessage(CSteamID speakerSteamID, string iconURL, EChatMode mode, Color color, bool isRich, string text)
    +ReceiveVoteStart(CSteamID origin, CSteamID target, byte votesNeeded)
    +ReceiveVoteUpdate(byte voteYes, byte voteNo)
    +ReceiveVoteStop(EVotingMessage message)
    +ReceiveVoteMessage(EVotingMessage message)
    +ReceiveSubmitVoteRequest(in ServerInvocationContext context, bool vote)
    +ReceiveCallVoteRequest(in ServerInvocationContext context, CSteamID target)
    +sendVote(bool vote)
    +sendCallVote(CSteamID target)
    +ReceiveChatEntry(CSteamID owner, string iconURL, EChatMode mode, Color color, bool rich, string text)
    +ReceiveChatRequest(in ServerInvocationContext context, byte flags, string text)
    +sendChat(EChatMode mode, string text)
    +clientSendMessage_UnityEvent(EChatMode mode, string text, ClientTextChatMessenger messenger)
    +serverSendMessage_UnityEvent(string text, Color color, string iconURL, bool useRichTextFormatting, ServerTextChatMessenger messenger)
    +say(CSteamID target, string text, Color color, bool isRich = false)
    +say(CSteamID target, string text, Color color, EChatMode mode, bool isRich = false)
    +say(string text, Color color, bool isRich = false)
    +serverSendMessage(string text, Color color, SteamPlayer fromPlayer = null, SteamPlayer toPlayer = null, EChatMode mode = EChatMode.SAY, string iconURL = null, bool useRichTextFormatting = false)

BarricadeManager [Class]:
    +getBarricadesInRadius(Vector3 center, float sqrRadius, List<RegionCoordinate> search, List<Transform> result)
    +getBarricadesInRadius(Vector3 center, float sqrRadius, ushort plant, List<Transform> result)
    +getBarricadesInRadius(Vector3 center, float sqrRadius, List<Transform> result)
    +tellBarricadeOwnerAndGroup(CSteamID steamID, byte x, byte y, ushort plant, ushort index, ulong newOwner, ulong newGroup)
    +transformBarricade(Transform transform, Vector3 point, Quaternion rotation)
    +tellTransformBarricade(CSteamID steamID, byte x, byte y, ushort plant, uint instanceID, Vector3 point, byte angle_x, byte angle_y, byte angle_z)
    +ServerSetBarricadeTransform(Transform transform, Vector3 position, Quaternion rotation)
    +InternalSetBarricadeTransform(byte x, byte y, ushort plant, BarricadeDrop barricade, Vector3 point, Quaternion rotation)
    +askTransformBarricade(CSteamID steamID, byte x, byte y, ushort plant, uint instanceID, Vector3 point, byte angle_x, byte angle_y, byte angle_z)
    +poseMannequin(Transform transform, byte poseComp)
    +tellPoseMannequin(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte poseComp)
    +ServerSetMannequinPose(InteractableMannequin mannequin, byte poseComp)
    +InternalSetMannequinPose(InteractableMannequin mannequin, byte x, byte y, ushort plant, byte poseComp)
    +askPoseMannequin(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte poseComp)
    +tellUpdateMannequin(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte[] state)
    +updateMannequin(Transform transform, EMannequinUpdateMode updateMode)
    +askUpdateMannequin(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte mode)
    +rotDisplay(Transform transform, byte rotComp)
    +tellRotDisplay(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte rotComp)
    +askRotDisplay(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte rotComp)
    +tellBarricadeHealth(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte hp)
    +salvageBarricade(Transform transform)
    +askSalvageBarricade(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +tellTank(CSteamID steamID, byte x, byte y, ushort plant, ushort index, ushort amount)
    +updateTank(Transform transform, ushort amount)
    +updateSign(Transform transform, string newText)
    +tellUpdateSign(CSteamID steamID, byte x, byte y, ushort plant, ushort index, string newText)
    +ServerSetSignText(InteractableSign sign, string newText)
    +ServerSetSignTextInternal(InteractableSign sign, BarricadeRegion region, byte x, byte y, ushort plant, string trimmedText)
    +askUpdateSign(CSteamID steamID, byte x, byte y, ushort plant, ushort index, string newText)
    +updateStereoTrack(Transform transform, Guid newTrack)
    +ServerSetStereoTrack(InteractableStereo stereo, Guid track)
    +ServerSetStereoTrackInternal(InteractableStereo stereo, byte x, byte y, ushort plant, BarricadeRegion region, Guid track)
    +tellUpdateStereoTrack(CSteamID steamID, byte x, byte y, ushort plant, ushort index, Guid newTrack)
    +askUpdateStereoTrack(CSteamID steamID, byte x, byte y, ushort plant, ushort index, Guid newTrack)
    +updateStereoVolume(Transform transform, byte newVolume)
    +tellUpdateStereoVolume(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte newVolume)
    +askUpdateStereoVolume(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte newVolume)
    +transferLibrary(Transform transform, byte transaction, uint delta)
    +tellTransferLibrary(CSteamID steamID, byte x, byte y, ushort plant, ushort index, uint newAmount)
    +askTransferLibrary(CSteamID steamID, byte x, byte y, ushort plant, ushort index, byte transaction, uint delta)
    +toggleSafezone(Transform transform)
    +ServerSetSafezonePowered(InteractableSafezone safezone, bool isPowered)
    +ServerSetSafezonePoweredInternal(InteractableSafezone safezone, byte x, byte y, ushort plant, BarricadeRegion region, bool isPowered)
    +tellToggleSafezone(CSteamID steamID, byte x, byte y, ushort plant, ushort index, bool isPowered)
    +askToggleSafezone(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +toggleOxygenator(Transform transform)
    +ServerSetOxygenatorPowered(InteractableOxygenator oxygenator, bool isPowered)
    +ServerSetOxygenatorPoweredInternal(InteractableOxygenator oxygenator, byte x, byte y, ushort plant, BarricadeRegion region, bool isPowered)
    +tellToggleOxygenator(CSteamID steamID, byte x, byte y, ushort plant, ushort index, bool isPowered)
    +askToggleOxygenator(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +toggleSpot(Transform transform)
    +ServerSetSpotPowered(InteractableSpot spot, bool isPowered)
    +ServerSetSpotPoweredInternal(InteractableSpot spot, byte x, byte y, ushort plant, BarricadeRegion region, bool isPowered)
    +tellToggleSpot(CSteamID steamID, byte x, byte y, ushort plant, ushort index, bool isPowered)
    +askToggleSpot(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +sendFuel(Transform transform, ushort fuel)
    +tellFuel(CSteamID steamID, byte x, byte y, ushort plant, ushort index, ushort fuel)
    +toggleGenerator(Transform transform)
    +ServerSetGeneratorPowered(InteractableGenerator generator, bool isPowered)
    +ServerSetGeneratorPoweredInternal(InteractableGenerator generator, byte x, byte y, ushort plant, BarricadeRegion region, bool isPowered)
    +tellToggleGenerator(CSteamID steamID, byte x, byte y, ushort plant, ushort index, bool isPowered)
    +askToggleGenerator(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +toggleFire(Transform transform)
    +ServerSetFireLit(InteractableFire fire, bool isLit)
    +ServerSetFireLitInternal(InteractableFire fire, byte x, byte y, ushort plant, BarricadeRegion region, bool isLit)
    +tellToggleFire(CSteamID steamID, byte x, byte y, ushort plant, ushort index, bool isLit)
    +askToggleFire(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
    +toggleOven(Transform transform)
    +ServerSetOvenLit(InteractableOven oven, bool isLit)
    +ServerSetOvenLitInternal(InteractableOven oven, byte x, byte y, ushort plant, BarricadeRegion region, bool isLit)